### ISSUE TITLE
Does not upgrade 7.1U > 8.0 properly.

### ISSUE THREAD

**Issue by Suika** [FlashpointProject/FlashpointUltimateUpdater#1]
When executing `python3 update.py /path/to/FlashPoint --update 7.1 8.0`, the script detects files that are on disk as missing.
Queue ~17k `File from current index not found. Queued for download: Flashpoint/Data/*` messages and the script will start downloading data that I already have.

Unless I'm missing something, this is not how it should be. Because the files that are marked as missing are there.

**Comment by XXLuigiMario** [comment]
Make sure you're pointing to the folder containing the `Flashpoint` folder, not the `Flashpoint` folder itself. If your `Flashpoint` folder is located at `C:\Flashpoint 7.1 Ultimate\Flashpoint` you must specify `C:\Flashpoint 7.1 Ultimate`

**Comment by Suika** [comment]
```
# root @ server in /path/to/FlashPoint [5:59:49]
$ l
total 1.4M
drwxr-xr-x 1 root  root   268 Apr 30 05:34 .
drwxr-xr-x 1 root  root  2.7K Apr 29 19:08 ..
-rw-r--r-- 1 root  root  1.3M Jan 24 04:35 changelog.txt
drwx------ 1 root  root   120 Jan 24 09:06 Data
drwx------ 1 root  root  7.4K Jan 24 09:07 Extras
drwx------ 1 root  root   594 Jan 24 09:07 FPSoftware
drwx------ 1 root  root   646 Jan 25 00:14 Launcher
-rw-r--r-- 1 root  root   15K Jan 24 04:34 readme.txt
-rw-r--r-- 1 root  root   326 Dec 25 16:53 Saves Manager - Backup.bat
-rw-r--r-- 1 root  root   711 Dec 25 16:53 Saves Manager - Restore.bat
drwx------ 1 root  root  2.7K Jan 24 11:33 Server
-rw-r--r-- 1 root  root  2.5K Dec 26 03:12 Start Flashpoint.lnk
drwxr-xr-x 1 root  root  506K Apr 30 05:43 .tmp
```

Forgot to mention, running it on linux.

**Comment by pintassilgo** [comment]
I'm also experiencing issues, but from 6.3 and on Windows 10.

I ran FlashpointUpdaterQt.exe (0.3b), it took ~8 hours to process  the update, but at the very end an alert showed up saying that some random .png file was in use (but there was nothing open). I dismissed it, then the Updater was saying that the update had been completed.

But all the content on Launcher directory was erased, so I can't open Flashpoint. Then I downloaded the Launcher and extracted it to the same folder, but just after opening the .exe they asked me for a folder (so I pointed to the parent folder, the Flashpoint root) and said it would install Flashpoint Infinity on it. I dismissed and closed, because I already have Flashpoint Update. One thing I noticed is that the Launched was named FlashpointLauncher.exe, but after the redownload it's Flashpoint.exe.

Oh, and if I run the Updater again, it still says my version is 6.3.

Please, what should I do?

Now there's a .tmp folder with more than a million files on it, while all the rest of the Flashpoint folder (Data, Launcher etc.) has only 6GB.

**Comment by XXLuigiMario** [comment]
@pintassilgo What happened in your case is that Windows Defender must have opened on of your files at random to scan it, preventing the Updater from moving it and halting the updater.
I'll add a warning to exclude the Flashpoint folder from scans as this seems to be a rather common issue. It's unfortunate that Windows Defender works this way as it leaves the application with no other recourse than to retry opening the file hoping it left go of its handle.
In addition, it's likely that disabling Windows Defender will greatly speed up the update process.

To fix your Flashpoint install, exclude the root folder from scans and run the updater again with the same settings. It should take care to resume the update and finish setting up the directory structure properly.

**Comment by XXLuigiMario** [comment]
@pintassilgo What happened in your case is that Windows Defender must have opened one of your files at random to scan it, preventing the Updater from moving it and halting the updater.
I'll add a warning to exclude the Flashpoint folder from scans as this seems to be a rather common issue. It's unfortunate that Windows Defender works this way as it leaves the application with no other recourse than to retry opening the file hoping it let go of its handle.
In addition, it's likely that disabling Windows Defender will greatly speed up the update process.

To fix your Flashpoint install, exclude the root folder from scans and run the updater again with the same settings. It should take care to resume the update and finish setting up the directory structure properly.

**Comment by pintassilgo** [comment]
Thanks for the quick reply. Now I'm running the Updater again, but it seems it would take another ~8 hours. Wouldn't be possible to identify that almost everything has already been done? Verifying checksums, I don't know...

**Comment by XXLuigiMario** [comment]
@pintassilgo That's exactly what the first step does. The first step is repeated every time, but it will skip the downloading step if not required.

**Comment by pintassilgo** [comment]
So almost 2 hours later it happened again.

> Update failed
> [WinError 32] O arquivo já está sendo usado por outro processo: '\\\\?\\H:\\Jogos\\Flashpoint\\logs\\update_2020-05-28_10-39-06.log'

(File is already in use by another process)

Real-time protection is disabled and I also added the entire Flashpoint folder as an exception.

Any suggestion? How to disable logging?

**Comment by pintassilgo** [comment]
That was during "Task Start: Removing obsolete files...". Shouldn't the update be able to skip these non-critical erros without breaking the entire update?

**Comment by pintassilgo** [comment]
Yep, that was it. Now it worked.

We can't put Updater inside Flashpoint folder.

**Comment by sjkorvin** [comment]
I just tried updating Flashpoint 8.0 to Flashpoint 8.1 using Flashpoint Updater 0.4. My directory structure looks as such:

<img width="723" alt="explorer_2020-07-09_12-20-33" src="https://user-images.githubusercontent.com/50928154/87065216-c168e900-c1de-11ea-8f41-650290d908c9.png">

I can see that everything that downloaded is in the .tmp directory. After everything had downloaded, I had received an error stating `Index error: pop from empty list` and that the update had failed.. My log file is nearly 270 megabytes.

**Comment by Geemer** [comment]
Please tell me what I'm doing wrong, because it looks like the updater (0.4) wants to download EVERYTHING again even though I point it to the folder updater 0.3b created when it updated Flashpoint 7.1U to 8.0 **also by downloading everything again**, taking 10 hours.
The logs say the files are missing, but they're very clearly not and even have the same hash.
See attached screenshot:
![Flashpoint WHY](https://user-images.githubusercontent.com/6912397/87185227-b64eaf80-c2e9-11ea-8853-53eb921cfbac.png)

It properly detected the old version is 8.0, so it shouldn't be a case of it looking in the wrong folders.
At the point I cut it short, it'd already downloaded 16 gb of data, claiming to only be 6% in.

**Comment by XXLuigiMario** [comment]
@Geemer It looks like you should be using `Flashpoint Ultimate` as your root folder.
With your current configuration, it's looking in `Flashpoint Ultimate\Flashpoint\Flashpoint\htdocs\...` which does not exist.

**Comment by Geemer** [comment]
@XXLuigiMario Thanks for the quick reply!

I actually did select `Flashpoint Ultimate` as root folder, the updater then took it upon itself to append `\Flashpoint` to it.
The `.tmp` folder ended up at `Flashpoint Ultimate\Flashpoint\.tmp`.

I just tried manually removing the extraneous `\Flashpoint` from the path, that creates the `.tmp` folder beside the `Flashpoint` folder and appears to work properly from then on.

**Comment by XXLuigiMario** [comment]
> 
> 
> @XXLuigiMario Thanks for the quick reply!
> 
> I actually did select `Flashpoint Ultimate` as root folder, the updater then took it upon itself to append `\Flashpoint` to it.
> The `.tmp` folder ended up at `Flashpoint Ultimate\Flashpoint\.tmp`.
> 
> I just tried manually removing the extraneous `\Flashpoint` from the path, that creates the `.tmp` folder beside the `Flashpoint` folder and appears to work properly from then on.

Yikes. You are very much right, the updater will autodetect the version of Flashpoint by defining a file as an anchor, for this we use `changelog.txt`. However, this was set with `Flashpoint` as the root index path in mind. Once it finds `changelog.txt` it will setthe root path to that of its parent folder, meaning if the file is found under `Desktop\Flashpoint Ultimate\Flashpoint\changelog.txt`, the root path will be set to `Desktop\Flashpoint Ultimate\Flashpoint\`.
However, this is no good, as the paths in the index contain `Flashpoint`, which is what happened in your case.
I'll submit a fix ASAP.

**Comment by Suika** [comment]
I've run the updater again and this time it didn't try to re-download everything. Seems ok, thanks. Closing.
